#!/usr/bin/env bash
set -o errexit -o pipefail -o nounset

git clone https://github.com/fippli/climate.git && \
  ( cd climate && \
    bash main install ) && \
  rm -rf climate && \
  echo "Export ${package_bin} to your path"
