#!/usr/bin/env bash
set -o errexit -o pipefail -o nounset

git clone https://github.com/codewell/climate.git && \
  ( cd climate && \
    bash main install ) && \
  rm -rf climate && \
  echo "Export ${HOME}/.climate/bin to your path"
