#!/usr/bin/env bash
set -o errexit -o pipefail -o nounset
set -x

##
#   •••• ••   ••  ••••   •••• ••  ••
#  •••   • • • • ••  •• •••   ••  ••
#    ••• •• • •• ••••••   ••• ••••••
#  ••••  ••   •• ••  •• ••••  ••  ••
# 
#  •••••••••••••••••••••••••••••••••
# 
#  Script MAnager for SHell scripts
#
##

main_script_path=${BASH_SOURCE[0]}
base_dir="$(dirname "${main_script_path}")"

source_files () {
  for src in "${base_dir}/"*.sh; do
    if [ "${src}" = "${main_script_path}" ]; then
      continue
    fi

    [ -f "${src}" ] && . "${src}"
  done
}

cleanup_main () {
  echo "Cleaning up!"
}

main () {
  source_files "${base_dir}"
  read_options "$@"
  trap cleanup_main EXIT
}

main "$@"

