#!/usr/bin/env bash
set -o errexit -o pipefail -o nounset

##
# Script MAnager for SHell scripts
# Main script
##

main_script_path=${BASH_SOURCE[0]}
base_dir="$(dirname "${main_script_path}")"

source_files () {
  for src in "${base_dir}/"*.sh; do
    if [ "${src}" = "${main_script_path}" ]; then
      continue
    fi

    [ -f "${src}" ] && . "${src}"
  done
}

main () {
  source_files "${base_dir}"
  read_options "$@"
}

main "$@"

